---
 
- hosts: all
  connection: local
  gather_facts: yes

  vars_files:
    - vars/main.yml
   
  roles:
    - debops.gunicorn
    - bennojoy.nginx
    - phansible.sqlite
    - andrewrothstein.supervisord
    - vitalk.flaskapp
    
  
 