---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - role: debops.gunicorn
    - role: bennojoy.nginx
    - role: phansible.sqlite
    - role: andrewrothstein.supervisord
