---
- name: Install Nginx
  hosts: all
  remote_user: root
  
  roles:
    - role: nginx
    
- name: Install SQlite
  hosts: all
  remote_user: root
  
  roles:
    - role: Sqlite
    
- name: Install Supervisor
  hosts: all
  remote_user: root
  
  roles:
    - role: Supervisord
    
- name: Install Gunicorn
  hosts: all
  remote_user: root
  
  roles:
    - role: Gunicorn
    
- name: Install flask
  hosts: all
  remote_user: root
  
  roles:
    - role: Flask
